## numpy 使用简介

numpy特别常用

[中文官网](https://www.numpy.org.cn/)

这里就简单介绍一下，还是，查找资料的能力很重要

### numpy 的安装
```
pip install numpy
```

### 创建一个numpy

In [1]:
# 最简单
import numpy as np
x = np.array([1, 2, 3])
print(x)

[1 2 3]


In [1]:
# 多于一个维度
import numpy as np
a = np.array([[1,  2],  [3,  4]])
print(a)

[[1 2]
 [3 4]]


In [2]:
# 最小维度
import numpy as np
a = np.array([1, 2, 3, 4, 5], ndmin=2)
print(a)

[[1 2 3 4 5]]


In [3]:
import numpy as np
a = np.array([1,  2,  3], dtype=complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


numpy 能够支持许多数据类型，几乎囊括了你能想到的所有

### 数组属性

In [4]:
x = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)
print(x.ndim)
print(x.shape)
print(x.size)
print(x.dtype)

2
(2, 3)
6
float64


### 创建空的数组

In [6]:
x = np.empty((3,2), dtype=int)
print(x)

[[0 0]
 [0 0]
 [0 0]]


In [8]:
y = np.zeros((5,3), dtype=int)
print(y)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [9]:
x=np.ones(5)
print(x)

[1. 1. 1. 1. 1.]


### numpy 的切片与索引
python 中几乎都是左闭右开

In [11]:
a = np.arange(10)
print(a)
print(a[3])
print(a[-1])
print(a[-2])
b = a[0:2]
print(b)
c = a[:-1]
print(c)
d = a[2:7:2]
print(d)

[0 1 2 3 4 5 6 7 8 9]
3
9
8
[0 1]
[0 1 2 3 4 5 6 7 8]
[2 4 6]


In [5]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a)


[[1 2 3]
 [3 4 5]
 [4 5 6]]


In [18]:
print(a[1])


[3 4 5]


In [6]:
print(a[:,1])
print(a[...,1])

[2 4 5]
[2 4 5]


In [21]:
print(a[...,1:])

[[2 3]
 [4 5]
 [5 6]]


### 数组的广播
你可以简单地对有相同shape的numpy数组进行按元素运算

如果shape不同，则按照以下规则进行广播后计算

- 让所有输入数组都向其中形状最长的数组看齐，形状中不足的部分都通过在前面加 1 补齐。
- 输出数组的形状是输入数组形状的各个维度上的最大值。
- 如果输入数组的某个维度和输出数组的对应维度的长度相同或者其长度为 1 时，这个数组能够用来计算，否则出错。
- 当输入数组的某个维度的长度为 1 时，沿着此维度运算时都用此维度上的第一组值。

[来源](https://www.runoob.com/numpy/numpy-broadcast.html)

个人建议

在你特别熟练掌握这个东西之前，不要使用过于复杂的操作

In [7]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[4, 5, 6], [1, 2, 3]])
z = np.array([1, 2, 3])
print(x + y)
print(x + z)

[[5 7 9]
 [5 7 9]]
[[2 4 6]
 [5 7 9]]


### 数学函数
numpy 内置了许多直接对数组进行操作的数学函数

np.sin(), np.exp()等

也提供np.pi等常量

一般而言，使用这些方法会快于自己操作，使用时查找自资料

In [8]:
x = np.arange(5)
print(x)
x = np.exp(x)
print(x)



[0 1 2 3 4]
[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]


### numpy 统计函数

median, amin, amax几乎你能想到的所有

In [9]:
a = np.array([[1, 2, 3],[4, 5, 6]])
print(np.amax(a))
print(np.amax(a, axis=0))
print(np.amax(a, axis=1))


6
[4 5 6]
[3 6]


### numpy 保存
numpy也提供了保存numpy数组的方法，并且实践下来该方法很快

In [31]:
x = np.arange(10)
np.save('test', x)


In [32]:
x = np.load('test.npy')
print(x)

[0 1 2 3 4 5 6 7 8 9]


也提供了保存多个数组到一个文件的方法，使用时自行查询
